//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldOfFootball.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WorldOfFootball.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap background1 {
            get {
                object obj = ResourceManager.GetObject("background1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap captain_band {
            get {
                object obj = ResourceManager.GetObject("captain_band", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose team.
        /// </summary>
        internal static string chooseTeamEn {
            get {
                return ResourceManager.GetString("chooseTeamEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberite reprezentaciju.
        /// </summary>
        internal static string chooseTeamHr {
            get {
                return ResourceManager.GetString("chooseTeamHr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap goal {
            get {
                object obj = ResourceManager.GetObject("goal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LeftArrow {
            get {
                object obj = ResourceManager.GetObject("LeftArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap loading1 {
            get {
                object obj = ResourceManager.GetObject("loading1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap location_mark {
            get {
                object obj = ResourceManager.GetObject("location_mark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo_color {
            get {
                object obj = ResourceManager.GetObject("logo-color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Logo2 {
            get {
                object obj = ResourceManager.GetObject("Logo2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Maradona {
            get {
                object obj = ResourceManager.GetObject("Maradona", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not selected a language and a championship.
        /// </summary>
        internal static string messageChooseLangAndChampEn {
            get {
                return ResourceManager.GetString("messageChooseLangAndChampEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niste izabrali jezik i prvenstvo.
        /// </summary>
        internal static string messageChooseLangAndChampHr {
            get {
                return ResourceManager.GetString("messageChooseLangAndChampHr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not chosen a favorite team.
        /// </summary>
        internal static string messageFavoriteTeamEn {
            get {
                return ResourceManager.GetString("messageFavoriteTeamEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niste izabrali omiljenu reprezentaciju.
        /// </summary>
        internal static string messageFavoriteTeamHr {
            get {
                return ResourceManager.GetString("messageFavoriteTeamHr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to set {0} language and  {1} championship?.
        /// </summary>
        internal static string messageLangAndChampEn {
            get {
                return ResourceManager.GetString("messageLangAndChampEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da li ste sigurni da želite postaviti  {0} jezik i {1} prvenstvo?.
        /// </summary>
        internal static string messageLangAndChampHr {
            get {
                return ResourceManager.GetString("messageLangAndChampHr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to close the app?.
        /// </summary>
        internal static string messageLeavingEn {
            get {
                return ResourceManager.GetString("messageLeavingEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeste li sigurni da želite zatvoriti aplikaciju?.
        /// </summary>
        internal static string messageLeavingHr {
            get {
                return ResourceManager.GetString("messageLeavingHr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string messageWarningEn {
            get {
                return ResourceManager.GetString("messageWarningEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must choose 3 favorite players.
        /// </summary>
        internal static string messageWarningFavPlNotChosenEn {
            get {
                return ResourceManager.GetString("messageWarningFavPlNotChosenEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morate izabrati 3 najdraža igrača.
        /// </summary>
        internal static string messageWarningFavPlNotChosenHr {
            get {
                return ResourceManager.GetString("messageWarningFavPlNotChosenHr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upozorenje.
        /// </summary>
        internal static string messageWarningHr {
            get {
                return ResourceManager.GetString("messageWarningHr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can choose a maximum of 3 favorite players.
        /// </summary>
        internal static string messageWarningOnly3En {
            get {
                return ResourceManager.GetString("messageWarningOnly3En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Možete izabrati najviše 3 najdraža igrača.
        /// </summary>
        internal static string messageWarningOnly3Hr {
            get {
                return ResourceManager.GetString("messageWarningOnly3Hr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap people {
            get {
                object obj = ResourceManager.GetObject("people", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RightArrow {
            get {
                object obj = ResourceManager.GetObject("RightArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap settings {
            get {
                object obj = ResourceManager.GetObject("settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap star {
            get {
                object obj = ResourceManager.GetObject("star", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to engleski tekst.
        /// </summary>
        internal static string test {
            get {
                return ResourceManager.GetString("test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tshirt {
            get {
                object obj = ResourceManager.GetObject("tshirt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap yellow_card {
            get {
                object obj = ResourceManager.GetObject("yellow_card", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
